### ISSUE TITLE
Create and customize environment

### ISSUE THREAD

**Issue by BobNobrain** [MMM2017/cafe-root#6]
Make it possible to deploy server module at any (at least any Linux-driven) machine we have

**Comment by IzmaylovAndrey** [comment]
http://itnovella.ru/itnovella/2014/01/04/virtualnye-okruzheniya-v-python-virtualenv.html

**Comment by IzmaylovAndrey** [comment]
Короче в cafe-server/README.md инструкция. Лучше пока не будет. Пробуйте, господа. Создаём - запускаем - радуемся. Ну или не очень радуемся.

Все вопросы и пожелания - сюда(желательно)/в ЛС(не надо так).
